# Generated by Django 5.2.4 on 2025-07-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_createddate'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, related_name='bookmarkedPosts', to='post.post'),
        ),
    ]
