# Generated by Django 5.2.4 on 2025-07-07 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='createdDate',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 7, 7, 10, 5, 38, 246026, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='lastChanges',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
