# Generated by Django 5.2.4 on 2025-07-19 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_createddate_post_lastchanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdDate',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 7, 19, 13, 58, 29, 378078, tzinfo=datetime.timezone.utc)),
        ),
    ]
